### ISSUE TITLE
Script not working (Outdated)

### ISSUE THREAD

**Issue by hoemotion** [RithDev/Discord-MassDM#1]
You dont use _member intents_ which means that mass dm is __impossible__.
i have 2 working mass dm repos. 1 for selfbots and 1 for normal bots
- selfbot:
> **[[mass-dm-discord](https://github.com/hoemotion/mass-dm-discord)]**
- normal bot (very fast):
> **[[Karuma](https://github.com/hoemotion/Karuma)]**

Cheers 🚀

**Comment by RithDev** [comment]
It's still possible as its using discord.py version 1.4.2, if you update to 1.5.X obviously then it wont work but if people just use discord.py for selfbots then most likely they use v1.4.2.

**Comment by hoemotion** [comment]
> It's still possible as its using discord.py version 1.4.2, if you update to 1.5.X obviously then it wont work but if people just use discord.py for selfbots then most likely they use v1.4.2.

Nope tested it out with v1.4.2, new gateways arent bypassable. The only way of getting all members is scraping them with discum

**Comment by RithDev** [comment]
Must just be a you problem, I still usually use this script now and again when promoting servers and its never had a single issue so not quite sure why it does that for you. Scrapes members just fine so pretty confused to be honest.

**Comment by hoemotion** [comment]
> Must just be a you problem, I still usually use this script now and again when promoting servers and its never had a single issue so not quite sure why it does that for you. Scrapes members just fine so pretty confused to be honest.

Hmm okay, maybe its something with my pc

**Comment by RithDev** [comment]
> > Must just be a you problem, I still usually use this script now and again when promoting servers and its never had a single issue so not quite sure why it does that for you. Scrapes members just fine so pretty confused to be honest.
> 
> Hmm okay, maybe its something with my pc

I wouldn't call it a your PC problem though, might just be something discord.py or an discord api endpoint.
